name: node_url_shortener

services:
  postgres:
    image: postgres:latest
    container_name: node_url_shortener_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: node_url_shortener_redis
    restart: always
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      pull: true
    image: node_url_shortener_app:latest
    container_name: node_url_shortener_app
    restart: always
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
      - BASE_URL=${BASE_URL}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
